[package]
name = "lospec-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/bin/main.rs"
name = "lospec"

[dependencies]
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.11", features = [
    "rustls-tls",
], default_features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.36", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
colored = "2"
thiserror = "1"
